import turtle as T
import random
import time

# 画樱花的躯干(60,t)
def Tree1(branch, t):
    time.sleep(0.0005)
    if branch > 3:
        if 8 <= branch <= 12:
            if random.randint(0, 2) == 0:
                t.color('snow')  # 白
            else:
                t.color('lightcoral')  # 淡珊瑚色
            t.pensize(branch / 3)
        elif branch < 8:
            if random.randint(0, 1) == 0:
                t.color('snow')
            else:
                t.color('mistyrose')  # 淡珊瑚色
            t.pensize(branch / 2)
        else:
            t.color('sienna')  # 赭(zhě)色
            t.pensize(branch / 10)  # 6
        t.forward(branch)
        a = 1.5 * random.random()
        t.right(20 * a)
        b = 1.5 * random.random()
        Tree1(branch - 10 * b, t)
        t.left(40 * a)
        Tree1(branch - 10 * b, t)
        t.right(20 * a)
        t.up()
        t.backward(branch)
        t.down()


# 掉落的花瓣
def Petal1(m, t):
    for i in range(m):
        a = 200 - 400 * random.random()
        b = 10 - 20 * random.random()
        t.up()
        t.forward(b)
        t.left(90)
        t.forward(a)
        t.down()
        t.color('lightcoral')  # 淡珊瑚色
        t.circle(1)
        t.up()
        t.backward(a)
        t.right(90)
        t.backward(b)

# 绘图区域
t = T.Turtle()
# 画布大小
w = T.Screen()
t.hideturtle()  # 隐藏画笔
t.getscreen().tracer(200, 0)
w.screensize(200,200,bg='wheat')
t.left(90)
t.up()
t.backward(300)
t.down()
t.color('sienna')

# 画樱花的躯干
random.seed(7)
Tree1(60, t)
#画燕子
import turtle
turtle.penup()
turtle.goto(-460,160)
turtle.pendown()
turtle.begin_fill()
turtle.pensize(3)
turtle.circle(30,-30)
turtle.circle(30,240)
turtle.penup()
turtle.goto(-490,190)
turtle.pendown()
turtle.seth(0)
turtle.circle(18,150)
turtle.seth(125)
turtle.circle(100,60)
turtle.penup()
turtle.goto(-490,190)
turtle.pendown()
turtle.seth(0)
turtle.circle(-18,160)
turtle.seth(-125)
turtle.circle(-100,40)
turtle.seth(0)
turtle.circle(25,150)
turtle.seth(170)
turtle.fd(100)
turtle.seth(0)
turtle.fd(80)
turtle.seth(165)
turtle.fd(80)
turtle.seth(0)
turtle.fd(80)
turtle.circle(25,150)
turtle.fd(40)
turtle.color('black')
turtle.end_fill()
turtle.penup()
turtle.goto(-445,185)
turtle.seth(0)
turtle.pendown()
turtle.begin_fill()
turtle.circle(8,360)
turtle.color('white')
turtle.end_fill()
turtle.color('black')
turtle.pensize(6)
turtle.penup()
turtle.goto(-443,189)
turtle.pendown()
turtle.circle(2.5,360)
turtle.penup()
turtle.goto(-430,190)
turtle.pensize(4)
turtle.pendown()
turtle.seth(10)
turtle.fd(10)
turtle.seth(160)
turtle.fd(10)

# 掉落的花瓣
random.seed(7)
Petal1(200, t)

# 画樱花的躯干(60,t)
def Tree2(branch, t):
    time.sleep(0.0005)
    if branch > 3:
        if 8 <= branch <= 12:
            if random.randint(0, 2) == 0:
                t.color('limegreen')  # 绿色
            else:
                t.color('green')  # 绿色
            t.pensize(branch / 3)
        elif branch < 8:
            if random.randint(0, 1) == 0:
                t.color('seagreen')
            else:
                t.color('green')  #绿色
            t.pensize(branch / 2)
        else:
            t.color('sienna')  # 赭(zhě)色
            t.pensize(branch / 10)  
        t.forward(branch)
        a = 1.5 * random.random()
        t.right(20 * a)
        b = 1.5 * random.random()
        Tree2(branch - 10 * b, t)
        t.left(40 * a)
        Tree2(branch - 10 * b, t)
        t.right(20 * a)
        t.up()
        t.backward(branch)
        t.down()

# 掉落的花瓣
def Petal2(m, t):
    for i in range(m):
        a = 200 - 400 * random.random()
        b = 10 - 20 * random.random()
        t.up()
        t.forward(b)
        t.left(90)
        t.forward(a)
        t.down()
        t.color('wheat')  # 淡珊瑚色
        t.circle(1)
        t.up()
        t.backward(a)
        t.right(90)
        t.backward(b)


#青蛙
def frog():
    t.pencolor('Green')
    t.pensize(2)
    t.penup()
    t.goto(200,-250)
    t.pendown()
    t.seth(90)
    t.begin_fill()
    t.circle(10, 360)
    t.color('White')
    t.end_fill()
    t.color('Green')
    t.penup()
    t.seth(180)
    t.forward(10)
    t.pensize(5)
    t.pendown()
    t.seth(180)
    t.color('Black')
    t.forward(1)
    t.penup()
    t.color('Green')
    t.pensize(2)
    t.seth(0)
    t.forward(11)
    t.pendown()
    t.forward(10)
    t.seth(90)
    t.begin_fill()
    t.circle(-10, 360)
    t.color('White')
    t.end_fill()
    t.color('Green')
    t.penup()
    t.seth(0)
    t.forward(10)
    t.pensize(5)
    t.pendown()
    t.color('Black')
    t.forward(1)
    t.color('Green')
    t.penup()
    t.backward(1)
    t.seth(-60)
    t.forward(10)
    t.pensize(2)
    t.pendown()
    t.seth(-90)
    t.color('Green')
    t.circle(-20,180)
    t.seth(-90)
    t.circle(20, 45)
    t.seth(-135)
    t.forward(20)
    t.seth(-90)
    t.forward(25)
    t.backward(5)
    for i in [-45,-135]:
        t.seth(i)
        t.forward(5)
        t.backward(5)
    t.seth(90)
    t.forward(20)
    t.seth(45)
    t.forward(20)
    t.seth(-135)
    t.circle(20,270)
    t.seth(-45)
    t.forward(20)
    t.seth(-90)
    t.forward(25)
    t.backward(5)
    for i in [-45, -135]:
        t.seth(i)
        t.forward(5)
        t.backward(5)
    t.seth(90)
    t.forward(20)
    t.seth(135)
    t.forward(20)
    t.seth(-45)
    t.penup()
    t.circle(-20,90)
    t.pendown()
    t.seth(25)
    t.pensize(3)
    t.forward(30)
    t.seth(-125)
    t.forward(30)
    t.seth(55)
    t.forward(30)
    t.seth(-155)
    t.forward(30)
    t.seth(-135)
    t.circle(-20,90)
    t.seth(155)
    t.forward(30)
    t.seth(-55)
    t.forward(30)
    t.penup()
    t.goto(0,-300)
    t.seth(90)


#青蛙消失
def frog_disappear():
    t.pencolor('wheat')
    t.pensize(2)
    t.penup()
    t.goto(200,-250)
    t.pendown()
    t.seth(90)
    t.begin_fill()
    t.circle(10, 360)
    t.color('wheat')
    t.end_fill()
    t.color('wheat')
    t.penup()
    t.seth(180)
    t.forward(10)
    t.pensize(5)
    t.pendown()
    t.seth(180)
    t.color('wheat')
    t.forward(1)
    t.penup()
    t.color('wheat')
    t.pensize(2)
    t.seth(0)
    t.forward(11)
    t.pendown()
    t.forward(10)
    t.seth(90)
    t.begin_fill()
    t.circle(-10, 360)
    t.color('wheat')
    t.end_fill()
    t.color('wheat')
    t.penup()
    t.seth(0)
    t.forward(10)
    t.pensize(5)
    t.pendown()
    t.color('wheat')
    t.forward(1)
    t.color('wheat')
    t.penup()
    t.backward(1)
    t.seth(-60)
    t.forward(10)
    t.pensize(2)
    t.pendown()
    t.seth(-90)
    t.color('wheat')
    t.circle(-20,180)
    t.seth(-90)
    t.circle(20, 45)
    t.seth(-135)
    t.forward(20)
    t.seth(-90)
    t.forward(25)
    t.backward(5)
    for i in [-45,-135]:
        t.seth(i)
        t.forward(5)
        t.backward(5)
    t.seth(90)
    t.forward(20)
    t.seth(45)
    t.forward(20)
    t.seth(-135)
    t.circle(20,270)
    t.seth(-45)
    t.forward(20)
    t.seth(-90)
    t.forward(25)
    t.backward(5)
    for i in [-45, -135]:
        t.seth(i)
        t.forward(5)
        t.backward(5)
    t.seth(90)
    t.forward(20)
    t.seth(135)
    t.forward(20)
    t.seth(-45)
    t.penup()
    t.circle(-20,90)
    t.pendown()
    t.seth(25)
    t.pensize(3)
    t.forward(30)
    t.seth(-125)
    t.forward(30)
    t.seth(55)
    t.forward(30)
    t.seth(-155)
    t.forward(30)
    t.seth(-135)
    t.circle(-20,90)
    t.seth(155)
    t.forward(30)
    t.seth(-55)
    t.forward(30)
    t.penup()
    t.goto(0,-300)
    t.seth(90)


random.seed(7)
Petal2(200, t)
frog()
#燕子消失
turtle.hideturtle()
t.penup()
t.pencolor('wheat')
t.goto(-600,160)
t.seth(0)
t.pensize(250)
t.pendown()
t.fd(240)
t.penup()
t.pensize(2)
t.goto(0,-300)
t.pendown()
t.seth(90)
random.seed(7)
Tree2(60, t)
frog_disappear()


# 画樱花的躯干(60,t)
def Tree3(branch, t):
    time.sleep(0.0005)
    if branch > 3:
        if 8 <= branch <= 12:
            if random.randint(0, 2) == 0:
                t.color('orange')  # 橙
            else:
                t.color('darkorange')  # 橙色
            t.pensize(branch / 3)
        elif branch < 8:
            if random.randint(0, 1) == 0:
                t.color('darkorange')
            else:
                t.color('darkorange')  #橙色
            t.pensize(branch / 2)
        else:
            t.color('sienna')  # 赭(zhě)色
            t.pensize(branch / 10)  # 6
        t.forward(branch)
        a = 1.5 * random.random()
        t.right(20 * a)
        b = 1.5 * random.random()
        Tree3(branch - 10 * b, t)
        t.left(40 * a)
        Tree3(branch - 10 * b, t)
        t.right(20 * a)
        t.up()
        t.backward(branch)
        t.down()


# 掉落的花瓣
def Petal3(m, t):
    for i in range(m):
        a = 200 - 400 * random.random()
        b = 10 - 20 * random.random()
        t.up()
        t.forward(b)
        t.left(90)
        t.forward(a)
        t.down()
        t.color('darkorange')  # 橙色
        t.circle(1)
        t.up()
        t.backward(a)
        t.right(90)
        t.backward(b)
# 草堆


turtle.penup()
turtle.goto(300, -130)
turtle.seth(0)
turtle.pendown()
turtle.width(7)
turtle.pencolor('orange')
turtle.begin_fill()
turtle.color("orange")
for i in range(4):
    turtle.pendown()
    turtle.fd(60)
    turtle.circle(10, 90)
turtle.fd(60)
turtle.penup()
turtle.fd(30)
for i in range(4):
    turtle.pendown()
    turtle.fd(60)
    turtle.circle(10, 90)
turtle.fd(60)
turtle.penup()
turtle.fd(30)
for i in range(4):
    turtle.pendown()
    turtle.fd(60)
    turtle.circle(10, 90)
turtle.penup()
turtle.fd(60)
turtle.circle(10, 45)
turtle.pendown()
turtle.fd(110)
turtle.circle(10, 45)
turtle.fd(60)
turtle.circle(10, 90)
turtle.fd(60)
turtle.circle(10, 45)
turtle.fd(110)
turtle.penup()
turtle.circle(0, 135)
turtle.fd(68)
turtle.circle(9, 45)
turtle.pendown()
turtle.fd(110)

turtle.penup()
turtle.goto(300, -130)
turtle.seth(0)
turtle.fd(60)
turtle.circle(10, 45)
turtle.fd(110)
turtle.circle(10, 45)
turtle.fd(60)
turtle.pendown()
turtle.circle(10, 90)
turtle.fd(60)
turtle.circle(10, 45)
turtle.fd(110)
turtle.penup()
turtle.circle(0, 135)
turtle.fd(68)
turtle.circle(9, 45)
turtle.pendown()
turtle.fd(110)

turtle.penup()
turtle.goto(380, -130)
turtle.seth(0)
turtle.fd(60)
turtle.circle(10, 45)
turtle.fd(110)
turtle.circle(10, 45)
turtle.fd(60)
turtle.pendown()
turtle.circle(10, 90)
turtle.fd(60)
turtle.circle(10, 45)
turtle.fd(110)
turtle.penup()
turtle.circle(0, 135)
turtle.fd(70)
turtle.circle(9, 45)
turtle.pendown()
turtle.fd(110)
turtle.end_fill()
turtle.goto(300, -130)

turtle.width(10)
turtle.pencolor('chocolate')
turtle.penup()
turtle.goto(328, -25)
turtle.seth(0)
turtle.pendown()
turtle.fd(56)
turtle.penup()
turtle.fd(20)
turtle.pendown()
turtle.fd(58)
turtle.penup()
turtle.fd(17)
turtle.pendown()
turtle.fd(8)
turtle.penup()
turtle.fd(15)
turtle.pendown()
turtle.fd(58)
turtle.penup()
turtle.fd(7)
turtle.pendown()
turtle.seth(-90)
turtle.fd(67)

turtle.penup()
turtle.goto(356, 0)
turtle.seth(0)
turtle.pendown()
turtle.fd(56)
turtle.penup()
turtle.fd(20)
turtle.pendown()
turtle.fd(58)
turtle.penup()
turtle.fd(17)
turtle.pendown()
turtle.fd(6)
turtle.penup()
turtle.fd(15)
turtle.pendown()
turtle.fd(58)
turtle.penup()
turtle.fd(7)
turtle.pendown()
turtle.seth(-90)
turtle.fd(66)


# 画樱花的躯干
random.seed(7)
Tree3(60, t)
# 掉落的花瓣
random.seed(7)
Petal3(200, t)

#草堆消失
turtle.hideturtle()
turtle.penup()
turtle.goto(300, -130)
turtle.seth(0)
turtle.pendown()
turtle.width(7)
turtle.pencolor('orange')
turtle.begin_fill()
turtle.color("wheat")
for i in range(4):
    turtle.pendown()
    turtle.fd(60)
    turtle.circle(10, 90)
turtle.fd(60)
turtle.penup()
turtle.fd(30)
for i in range(4):
    turtle.pendown()
    turtle.fd(60)
    turtle.circle(10, 90)
turtle.fd(60)
turtle.penup()
turtle.fd(30)
for i in range(4):
    turtle.pendown()
    turtle.fd(60)
    turtle.circle(10, 90)
turtle.penup()
turtle.fd(60)
turtle.circle(10, 45)
turtle.pendown()
turtle.fd(110)
turtle.circle(10, 45)
turtle.fd(60)
turtle.circle(10, 90)
turtle.fd(60)
turtle.circle(10, 45)
turtle.fd(110)
turtle.penup()
turtle.circle(0, 135)
turtle.fd(68)
turtle.circle(9, 45)
turtle.pendown()
turtle.fd(110)

turtle.penup()
turtle.goto(300, -130)
turtle.seth(0)
turtle.fd(60)
turtle.circle(10, 45)
turtle.fd(110)
turtle.circle(10, 45)
turtle.fd(60)
turtle.pendown()
turtle.circle(10, 90)
turtle.fd(60)
turtle.circle(10, 45)
turtle.fd(110)
turtle.penup()
turtle.circle(0, 135)
turtle.fd(68)
turtle.circle(9, 45)
turtle.pendown()
turtle.fd(110)

turtle.penup()
turtle.goto(380, -130)
turtle.seth(0)
turtle.fd(60)
turtle.circle(10, 45)
turtle.fd(110)
turtle.circle(10, 45)
turtle.fd(60)
turtle.pendown()
turtle.circle(10, 90)
turtle.fd(60)
turtle.circle(10, 45)
turtle.fd(110)
turtle.penup()
turtle.circle(0, 135)
turtle.fd(70)
turtle.circle(9, 45)
turtle.pendown()
turtle.fd(110)
turtle.end_fill()
turtle.goto(300, -130)

turtle.width(10)
turtle.pencolor('wheat')
turtle.penup()
turtle.goto(328, -25)
turtle.seth(0)
turtle.pendown()
turtle.fd(56)
turtle.penup()
turtle.fd(20)
turtle.pendown()
turtle.fd(58)
turtle.penup()
turtle.fd(17)
turtle.pendown()
turtle.fd(8)
turtle.penup()
turtle.fd(15)
turtle.pendown()
turtle.fd(58)
turtle.penup()
turtle.fd(7)
turtle.pendown()
turtle.seth(-90)
turtle.fd(67)

turtle.penup()
turtle.goto(356, 0)
turtle.seth(0)
turtle.pendown()
turtle.fd(56)
turtle.penup()
turtle.fd(20)
turtle.pendown()
turtle.fd(58)
turtle.penup()
turtle.fd(17)
turtle.pendown()
turtle.fd(6)
turtle.penup()
turtle.fd(15)
turtle.pendown()
turtle.fd(58)
turtle.penup()
turtle.fd(7)
turtle.pendown()
turtle.seth(-90)
turtle.fd(66)

# 画樱花的躯干(60,t)

def Tree4(branch, t):
    time.sleep(0.0005)
    if branch > 3:
        if 8 <= branch <= 12:
            if random.randint(0, 2) == 0:
                t.color('white')  # 白
            else:
                t.color('white')  # 白色
            t.pensize(branch / 3)
        elif branch < 8:
            if random.randint(0, 1) == 0:
                t.color('white')
            else:
                t.color('white')  # 白色
            t.pensize(branch / 2)
        else:
            t.color('sienna')  # 赭(zhě)色
            t.pensize(branch / 10)  # 6
        t.forward(branch)
        a = 1.5 * random.random()
        t.right(20 * a)
        b = 1.5 * random.random()
        Tree4(branch - 10 * b, t)
        t.left(40 * a)
        Tree4(branch - 10 * b, t)
        t.right(20 * a)
        t.up()
        t.backward(branch)
        t.down()


# 掉落的花瓣
def Petal4(m, t):
    for i in range(m):
        a = 200 - 400 * random.random()
        b = 10 - 20 * random.random()
        t.up()
        t.forward(b)
        t.left(90)
        t.forward(a)
        t.down()
        t.color('white')  # 白色
        t.circle(1)
        t.up()
        t.backward(a)
        t.right(90)
        t.backward(b)

#雪人
def Snowman():
    t.penup()
    t.goto(300,-150)
    t.seth(0)
    t.pendown()
    t.pensize(2)
    t.color('Black')
    t.begin_fill()
    t.circle(30, 360)
    t.circle(-60, 360)
    t.color('White')
    t.end_fill()
    t.pensize(10)
    t.color('Black')
    t.seth(90)
    t.penup()
    t.forward(40)
    t.seth(180)
    t.forward(10)
    t.pendown()
    t.forward(3)
    t.penup()
    t.seth(0)
    t.forward(23)
    t.pendown()
    t.forward(3)
    t.seth(180)
    t.penup()
    t.forward(13)
    t.seth(-90)
    t.forward(10)
    t.pensize(2)
    t.pencolor('red')
    t.pendown()
    t.seth(-5)
    t.forward(40)
    t.seth(185)
    t.forward(40)
    t.penup()
    t.seth(-90)
    t.forward(40)
    t.seth(180)
    t.forward(30)
    t.pencolor('Black')
    t.seth(135)
    t.pendown()
    t.forward(60)
    t.penup()
    t.backward(60)
    t.seth(0)
    t.forward(60)
    t.seth(45)
    t.pendown()
    t.forward(60)
    t.penup()
    t.seth(90)


# 画樱花的躯干
random.seed(7)
Tree4(60, t)
# 掉落的花瓣
random.seed(7)
Petal4(200, t)
Snowman()
w.exitonclick()
